name: Deploy Production

on:
  push:
    branches:
      - "main"

jobs:
  deploy_production:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: Production
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_DATABASE_URL: ${{ secrets.DIRECT_DATABASE_URL }}
      SESSION_SIGNING_KEY: ${{ secrets.SESSION_SIGNING_KEY }}
      EXEC_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Run Prisma Migrate
        run: |
          npx prisma migrate deploy

      - name: Run Prisma SeedMain
        run: |
          npx prisma db seed -- --environment production

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link Vercel project
        run:
          vercel link --yes --project svelteship -t ${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run:
          vercel pull -t ${{ secrets.VERCEL_TOKEN }} --environment=production
          --yes

      - name: Build Project Artifacts
        run: vercel build --prod -t ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run:
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          --env DATABASE_URL=$DATABASE_URL --env
          DIRECT_DATABASE_URL=$DIRECT_DATABASE_URL --env
          SESSION_SIGNING_KEY=$SESSION_SIGNING_KEY --env EXEC_ENV=$EXEC_ENV
